parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Manager\PlayerManager:
        autowire: false
        autoconfigure: false
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\EventListener\WinnerListener:
        autowire: false
        autoconfigure: false
        arguments:
            $playerManager: '@App\Manager\PlayerManager'
        tags:
            - { name: kernel.event_listener, event: 'player.win', method: winner }
